<?php

namespace Melp\Cg\Php\Parser;

use Melp\Cg\Common\ParserException;
use Melp\Cg\Php\Node;
use Melp\Cg\Common\ScannerInterface;

class NamespaceParser extends Parser
{
    public function __construct()
    {
        parent::__construct(); // TODO: Change the autogenerated stub

        $this->parsers[]= new UseParser();
        $this->parsers[]= new DocCommentParser();
        $this->parsers[]= new ClassParser();
        $this->parsers[]= new FunctionParser();
    }


    public function match(ScannerInterface $scanner)
    {
        return $scanner->match('namespace ');
    }


    public function parse(ScannerInterface $scanner)
    {
        $node = new Node\Namespacex();

        $scanner->expect('namespace ');
        $scanner->skip();

        $node['name'] = $scanner->expectr(self::FQCN)[0];

        if ($scanner->match(';', true)) {
            $node['single'] = true;
        }

        $this->subparse($scanner, $node);

        return $node;
    }
}